# Generated by Django 3.2 on 2022-04-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
